name: Merge Schedule

on:
  pull_request:
    types: [opened, edited]
  schedule:
    # check https://crontab.guru/ for set up time
    - cron: "30 8 * * *"

jobs:
  merge_schedule:
    runs-on: ubuntu-latest
    steps:
      - name: Merge Schedule
        uses: gr2m/merge-schedule-action@v2.4.1
        with:
          merge_method: squash
          time_zone: "America/Edmonton"
          require_statuses_success: "true"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
